/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PresetsRouteImport } from './routes/presets'
import { Route as ExercisesChordsRouteImport } from './routes/exercises/chords'
import { Route as ExercisesIntervalsRouteImport } from './routes/exercises/intervals'
import { Route as ExercisesPitchRouteImport } from './routes/exercises/pitch'
import { Route as ExercisesRhythmRouteImport } from './routes/exercises/rhythm'
import { Route as ExercisesChordIdentificationIndexRouteImport } from './routes/exercises/chord-identification/index'
import { Route as ExercisesChordIdentificationCustomRouteImport } from './routes/exercises/chord-identification/custom'
import { Route as ExercisesIntervalComparisonIndexRouteImport } from './routes/exercises/interval-comparison/index'
import { Route as ExercisesIntervalComparisonCustomRouteImport } from './routes/exercises/interval-comparison/custom'
import { Route as ExercisesIntervalIdentificationIndexRouteImport } from './routes/exercises/interval-identification/index'
import { Route as ExercisesIntervalIdentificationCustomRouteImport } from './routes/exercises/interval-identification/custom'
import { Route as ExercisesMetreIdentificationIndexRouteImport } from './routes/exercises/metre-identification/index'
import { Route as ExercisesMetreIdentificationCustomRouteImport } from './routes/exercises/metre-identification/custom'
import { Route as ExercisesMultiIntervalIdentificationIndexRouteImport } from './routes/exercises/multi-interval-identification/index'
import { Route as ExercisesMultiIntervalIdentificationCustomRouteImport } from './routes/exercises/multi-interval-identification/custom'
import { Route as ExercisesPitchMatchingIndexRouteImport } from './routes/exercises/pitch-matching/index'
import { Route as ExercisesPitchMatchingCustomRouteImport } from './routes/exercises/pitch-matching/custom'
import { Route as ExercisesPulseTappingIndexRouteImport } from './routes/exercises/pulse-tapping/index'
import { Route as ExercisesPulseTappingCustomRouteImport } from './routes/exercises/pulse-tapping/custom'
import { Route as ExercisesRhythmErrorDetectionIndexRouteImport } from './routes/exercises/rhythm-error-detection/index'
import { Route as ExercisesRhythmErrorDetectionCustomRouteImport } from './routes/exercises/rhythm-error-detection/custom'
import { Route as ExercisesRhythmReadingIndexRouteImport } from './routes/exercises/rhythm-reading/index'
import { Route as ExercisesRhythmReadingCustomRouteImport } from './routes/exercises/rhythm-reading/custom'
import { Route as ExercisesRhythmRecognitionIndexRouteImport } from './routes/exercises/rhythm-recognition/index'
import { Route as ExercisesRhythmRecognitionCustomRouteImport } from './routes/exercises/rhythm-recognition/custom'
import { Route as ExercisesRhythmTapBackIndexRouteImport } from './routes/exercises/rhythm-tap-back/index'
import { Route as ExercisesRhythmTapBackCustomRouteImport } from './routes/exercises/rhythm-tap-back/custom'
import { Route as ExercisesSilentBarTimingIndexRouteImport } from './routes/exercises/silent-bar-timing/index'
import { Route as ExercisesSilentBarTimingCustomRouteImport } from './routes/exercises/silent-bar-timing/custom'
import { Route as ExercisesChordIdentificationLessonLessonIdRouteImport } from './routes/exercises/chord-identification/lesson.$lessonId'
import { Route as ExercisesIntervalComparisonLessonLessonIdRouteImport } from './routes/exercises/interval-comparison/lesson.$lessonId'
import { Route as ExercisesIntervalIdentificationLessonLessonIdRouteImport } from './routes/exercises/interval-identification/lesson.$lessonId'
import { Route as ExercisesMetreIdentificationLessonLessonIdRouteImport } from './routes/exercises/metre-identification/lesson.$lessonId'
import { Route as ExercisesMultiIntervalIdentificationLessonLessonIdRouteImport } from './routes/exercises/multi-interval-identification/lesson.$lessonId'
import { Route as ExercisesPitchMatchingLessonLessonIdRouteImport } from './routes/exercises/pitch-matching/lesson.$lessonId'
import { Route as ExercisesPulseTappingLessonLessonIdRouteImport } from './routes/exercises/pulse-tapping/lesson.$lessonId'
import { Route as ExercisesRhythmErrorDetectionLessonLessonIdRouteImport } from './routes/exercises/rhythm-error-detection/lesson.$lessonId'
import { Route as ExercisesRhythmReadingLessonLessonIdRouteImport } from './routes/exercises/rhythm-reading/lesson.$lessonId'
import { Route as ExercisesRhythmRecognitionLessonLessonIdRouteImport } from './routes/exercises/rhythm-recognition/lesson.$lessonId'
import { Route as ExercisesRhythmTapBackLessonLessonIdRouteImport } from './routes/exercises/rhythm-tap-back/lesson.$lessonId'
import { Route as ExercisesSilentBarTimingLessonLessonIdRouteImport } from './routes/exercises/silent-bar-timing/lesson.$lessonId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PresetsRoute = PresetsRouteImport.update({
  id: '/presets',
  path: '/presets',
  getParentRoute: () => rootRouteImport,
} as any)
const ExercisesChordsRoute = ExercisesChordsRouteImport.update({
  id: '/exercises/chords',
  path: '/exercises/chords',
  getParentRoute: () => rootRouteImport,
} as any)
const ExercisesIntervalsRoute = ExercisesIntervalsRouteImport.update({
  id: '/exercises/intervals',
  path: '/exercises/intervals',
  getParentRoute: () => rootRouteImport,
} as any)
const ExercisesPitchRoute = ExercisesPitchRouteImport.update({
  id: '/exercises/pitch',
  path: '/exercises/pitch',
  getParentRoute: () => rootRouteImport,
} as any)
const ExercisesRhythmRoute = ExercisesRhythmRouteImport.update({
  id: '/exercises/rhythm',
  path: '/exercises/rhythm',
  getParentRoute: () => rootRouteImport,
} as any)
const ExercisesChordIdentificationIndexRoute =
  ExercisesChordIdentificationIndexRouteImport.update({
    id: '/exercises/chord-identification/',
    path: '/exercises/chord-identification/',
    getParentRoute: () => rootRouteImport,
  } as any)
const ExercisesChordIdentificationCustomRoute =
  ExercisesChordIdentificationCustomRouteImport.update({
    id: '/exercises/chord-identification/custom',
    path: '/exercises/chord-identification/custom',
    getParentRoute: () => rootRouteImport,
  } as any)
const ExercisesIntervalComparisonIndexRoute =
  ExercisesIntervalComparisonIndexRouteImport.update({
    id: '/exercises/interval-comparison/',
    path: '/exercises/interval-comparison/',
    getParentRoute: () => rootRouteImport,
  } as any)
const ExercisesIntervalComparisonCustomRoute =
  ExercisesIntervalComparisonCustomRouteImport.update({
    id: '/exercises/interval-comparison/custom',
    path: '/exercises/interval-comparison/custom',
    getParentRoute: () => rootRouteImport,
  } as any)
const ExercisesIntervalIdentificationIndexRoute =
  ExercisesIntervalIdentificationIndexRouteImport.update({
    id: '/exercises/interval-identification/',
    path: '/exercises/interval-identification/',
    getParentRoute: () => rootRouteImport,
  } as any)
const ExercisesIntervalIdentificationCustomRoute =
  ExercisesIntervalIdentificationCustomRouteImport.update({
    id: '/exercises/interval-identification/custom',
    path: '/exercises/interval-identification/custom',
    getParentRoute: () => rootRouteImport,
  } as any)
const ExercisesMetreIdentificationIndexRoute =
  ExercisesMetreIdentificationIndexRouteImport.update({
    id: '/exercises/metre-identification/',
    path: '/exercises/metre-identification/',
    getParentRoute: () => rootRouteImport,
  } as any)
const ExercisesMetreIdentificationCustomRoute =
  ExercisesMetreIdentificationCustomRouteImport.update({
    id: '/exercises/metre-identification/custom',
    path: '/exercises/metre-identification/custom',
    getParentRoute: () => rootRouteImport,
  } as any)
const ExercisesMultiIntervalIdentificationIndexRoute =
  ExercisesMultiIntervalIdentificationIndexRouteImport.update({
    id: '/exercises/multi-interval-identification/',
    path: '/exercises/multi-interval-identification/',
    getParentRoute: () => rootRouteImport,
  } as any)
const ExercisesMultiIntervalIdentificationCustomRoute =
  ExercisesMultiIntervalIdentificationCustomRouteImport.update({
    id: '/exercises/multi-interval-identification/custom',
    path: '/exercises/multi-interval-identification/custom',
    getParentRoute: () => rootRouteImport,
  } as any)
const ExercisesPitchMatchingIndexRoute =
  ExercisesPitchMatchingIndexRouteImport.update({
    id: '/exercises/pitch-matching/',
    path: '/exercises/pitch-matching/',
    getParentRoute: () => rootRouteImport,
  } as any)
const ExercisesPitchMatchingCustomRoute =
  ExercisesPitchMatchingCustomRouteImport.update({
    id: '/exercises/pitch-matching/custom',
    path: '/exercises/pitch-matching/custom',
    getParentRoute: () => rootRouteImport,
  } as any)
const ExercisesPulseTappingIndexRoute =
  ExercisesPulseTappingIndexRouteImport.update({
    id: '/exercises/pulse-tapping/',
    path: '/exercises/pulse-tapping/',
    getParentRoute: () => rootRouteImport,
  } as any)
const ExercisesPulseTappingCustomRoute =
  ExercisesPulseTappingCustomRouteImport.update({
    id: '/exercises/pulse-tapping/custom',
    path: '/exercises/pulse-tapping/custom',
    getParentRoute: () => rootRouteImport,
  } as any)
const ExercisesRhythmErrorDetectionIndexRoute =
  ExercisesRhythmErrorDetectionIndexRouteImport.update({
    id: '/exercises/rhythm-error-detection/',
    path: '/exercises/rhythm-error-detection/',
    getParentRoute: () => rootRouteImport,
  } as any)
const ExercisesRhythmErrorDetectionCustomRoute =
  ExercisesRhythmErrorDetectionCustomRouteImport.update({
    id: '/exercises/rhythm-error-detection/custom',
    path: '/exercises/rhythm-error-detection/custom',
    getParentRoute: () => rootRouteImport,
  } as any)
const ExercisesRhythmReadingIndexRoute =
  ExercisesRhythmReadingIndexRouteImport.update({
    id: '/exercises/rhythm-reading/',
    path: '/exercises/rhythm-reading/',
    getParentRoute: () => rootRouteImport,
  } as any)
const ExercisesRhythmReadingCustomRoute =
  ExercisesRhythmReadingCustomRouteImport.update({
    id: '/exercises/rhythm-reading/custom',
    path: '/exercises/rhythm-reading/custom',
    getParentRoute: () => rootRouteImport,
  } as any)
const ExercisesRhythmRecognitionIndexRoute =
  ExercisesRhythmRecognitionIndexRouteImport.update({
    id: '/exercises/rhythm-recognition/',
    path: '/exercises/rhythm-recognition/',
    getParentRoute: () => rootRouteImport,
  } as any)
const ExercisesRhythmRecognitionCustomRoute =
  ExercisesRhythmRecognitionCustomRouteImport.update({
    id: '/exercises/rhythm-recognition/custom',
    path: '/exercises/rhythm-recognition/custom',
    getParentRoute: () => rootRouteImport,
  } as any)
const ExercisesRhythmTapBackIndexRoute =
  ExercisesRhythmTapBackIndexRouteImport.update({
    id: '/exercises/rhythm-tap-back/',
    path: '/exercises/rhythm-tap-back/',
    getParentRoute: () => rootRouteImport,
  } as any)
const ExercisesRhythmTapBackCustomRoute =
  ExercisesRhythmTapBackCustomRouteImport.update({
    id: '/exercises/rhythm-tap-back/custom',
    path: '/exercises/rhythm-tap-back/custom',
    getParentRoute: () => rootRouteImport,
  } as any)
const ExercisesSilentBarTimingIndexRoute =
  ExercisesSilentBarTimingIndexRouteImport.update({
    id: '/exercises/silent-bar-timing/',
    path: '/exercises/silent-bar-timing/',
    getParentRoute: () => rootRouteImport,
  } as any)
const ExercisesSilentBarTimingCustomRoute =
  ExercisesSilentBarTimingCustomRouteImport.update({
    id: '/exercises/silent-bar-timing/custom',
    path: '/exercises/silent-bar-timing/custom',
    getParentRoute: () => rootRouteImport,
  } as any)
const ExercisesChordIdentificationLessonLessonIdRoute =
  ExercisesChordIdentificationLessonLessonIdRouteImport.update({
    id: '/exercises/chord-identification/lesson/$lessonId',
    path: '/exercises/chord-identification/lesson/$lessonId',
    getParentRoute: () => rootRouteImport,
  } as any)
const ExercisesIntervalComparisonLessonLessonIdRoute =
  ExercisesIntervalComparisonLessonLessonIdRouteImport.update({
    id: '/exercises/interval-comparison/lesson/$lessonId',
    path: '/exercises/interval-comparison/lesson/$lessonId',
    getParentRoute: () => rootRouteImport,
  } as any)
const ExercisesIntervalIdentificationLessonLessonIdRoute =
  ExercisesIntervalIdentificationLessonLessonIdRouteImport.update({
    id: '/exercises/interval-identification/lesson/$lessonId',
    path: '/exercises/interval-identification/lesson/$lessonId',
    getParentRoute: () => rootRouteImport,
  } as any)
const ExercisesMetreIdentificationLessonLessonIdRoute =
  ExercisesMetreIdentificationLessonLessonIdRouteImport.update({
    id: '/exercises/metre-identification/lesson/$lessonId',
    path: '/exercises/metre-identification/lesson/$lessonId',
    getParentRoute: () => rootRouteImport,
  } as any)
const ExercisesMultiIntervalIdentificationLessonLessonIdRoute =
  ExercisesMultiIntervalIdentificationLessonLessonIdRouteImport.update({
    id: '/exercises/multi-interval-identification/lesson/$lessonId',
    path: '/exercises/multi-interval-identification/lesson/$lessonId',
    getParentRoute: () => rootRouteImport,
  } as any)
const ExercisesPitchMatchingLessonLessonIdRoute =
  ExercisesPitchMatchingLessonLessonIdRouteImport.update({
    id: '/exercises/pitch-matching/lesson/$lessonId',
    path: '/exercises/pitch-matching/lesson/$lessonId',
    getParentRoute: () => rootRouteImport,
  } as any)
const ExercisesPulseTappingLessonLessonIdRoute =
  ExercisesPulseTappingLessonLessonIdRouteImport.update({
    id: '/exercises/pulse-tapping/lesson/$lessonId',
    path: '/exercises/pulse-tapping/lesson/$lessonId',
    getParentRoute: () => rootRouteImport,
  } as any)
const ExercisesRhythmErrorDetectionLessonLessonIdRoute =
  ExercisesRhythmErrorDetectionLessonLessonIdRouteImport.update({
    id: '/exercises/rhythm-error-detection/lesson/$lessonId',
    path: '/exercises/rhythm-error-detection/lesson/$lessonId',
    getParentRoute: () => rootRouteImport,
  } as any)
const ExercisesRhythmReadingLessonLessonIdRoute =
  ExercisesRhythmReadingLessonLessonIdRouteImport.update({
    id: '/exercises/rhythm-reading/lesson/$lessonId',
    path: '/exercises/rhythm-reading/lesson/$lessonId',
    getParentRoute: () => rootRouteImport,
  } as any)
const ExercisesRhythmRecognitionLessonLessonIdRoute =
  ExercisesRhythmRecognitionLessonLessonIdRouteImport.update({
    id: '/exercises/rhythm-recognition/lesson/$lessonId',
    path: '/exercises/rhythm-recognition/lesson/$lessonId',
    getParentRoute: () => rootRouteImport,
  } as any)
const ExercisesRhythmTapBackLessonLessonIdRoute =
  ExercisesRhythmTapBackLessonLessonIdRouteImport.update({
    id: '/exercises/rhythm-tap-back/lesson/$lessonId',
    path: '/exercises/rhythm-tap-back/lesson/$lessonId',
    getParentRoute: () => rootRouteImport,
  } as any)
const ExercisesSilentBarTimingLessonLessonIdRoute =
  ExercisesSilentBarTimingLessonLessonIdRouteImport.update({
    id: '/exercises/silent-bar-timing/lesson/$lessonId',
    path: '/exercises/silent-bar-timing/lesson/$lessonId',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/presets': typeof PresetsRoute
  '/exercises/chords': typeof ExercisesChordsRoute
  '/exercises/intervals': typeof ExercisesIntervalsRoute
  '/exercises/pitch': typeof ExercisesPitchRoute
  '/exercises/rhythm': typeof ExercisesRhythmRoute
  '/exercises/chord-identification/custom': typeof ExercisesChordIdentificationCustomRoute
  '/exercises/interval-comparison/custom': typeof ExercisesIntervalComparisonCustomRoute
  '/exercises/interval-identification/custom': typeof ExercisesIntervalIdentificationCustomRoute
  '/exercises/metre-identification/custom': typeof ExercisesMetreIdentificationCustomRoute
  '/exercises/multi-interval-identification/custom': typeof ExercisesMultiIntervalIdentificationCustomRoute
  '/exercises/pitch-matching/custom': typeof ExercisesPitchMatchingCustomRoute
  '/exercises/pulse-tapping/custom': typeof ExercisesPulseTappingCustomRoute
  '/exercises/rhythm-error-detection/custom': typeof ExercisesRhythmErrorDetectionCustomRoute
  '/exercises/rhythm-reading/custom': typeof ExercisesRhythmReadingCustomRoute
  '/exercises/rhythm-recognition/custom': typeof ExercisesRhythmRecognitionCustomRoute
  '/exercises/rhythm-tap-back/custom': typeof ExercisesRhythmTapBackCustomRoute
  '/exercises/silent-bar-timing/custom': typeof ExercisesSilentBarTimingCustomRoute
  '/exercises/chord-identification/': typeof ExercisesChordIdentificationIndexRoute
  '/exercises/interval-comparison/': typeof ExercisesIntervalComparisonIndexRoute
  '/exercises/interval-identification/': typeof ExercisesIntervalIdentificationIndexRoute
  '/exercises/metre-identification/': typeof ExercisesMetreIdentificationIndexRoute
  '/exercises/multi-interval-identification/': typeof ExercisesMultiIntervalIdentificationIndexRoute
  '/exercises/pitch-matching/': typeof ExercisesPitchMatchingIndexRoute
  '/exercises/pulse-tapping/': typeof ExercisesPulseTappingIndexRoute
  '/exercises/rhythm-error-detection/': typeof ExercisesRhythmErrorDetectionIndexRoute
  '/exercises/rhythm-reading/': typeof ExercisesRhythmReadingIndexRoute
  '/exercises/rhythm-recognition/': typeof ExercisesRhythmRecognitionIndexRoute
  '/exercises/rhythm-tap-back/': typeof ExercisesRhythmTapBackIndexRoute
  '/exercises/silent-bar-timing/': typeof ExercisesSilentBarTimingIndexRoute
  '/exercises/chord-identification/lesson/$lessonId': typeof ExercisesChordIdentificationLessonLessonIdRoute
  '/exercises/interval-comparison/lesson/$lessonId': typeof ExercisesIntervalComparisonLessonLessonIdRoute
  '/exercises/interval-identification/lesson/$lessonId': typeof ExercisesIntervalIdentificationLessonLessonIdRoute
  '/exercises/metre-identification/lesson/$lessonId': typeof ExercisesMetreIdentificationLessonLessonIdRoute
  '/exercises/multi-interval-identification/lesson/$lessonId': typeof ExercisesMultiIntervalIdentificationLessonLessonIdRoute
  '/exercises/pitch-matching/lesson/$lessonId': typeof ExercisesPitchMatchingLessonLessonIdRoute
  '/exercises/pulse-tapping/lesson/$lessonId': typeof ExercisesPulseTappingLessonLessonIdRoute
  '/exercises/rhythm-error-detection/lesson/$lessonId': typeof ExercisesRhythmErrorDetectionLessonLessonIdRoute
  '/exercises/rhythm-reading/lesson/$lessonId': typeof ExercisesRhythmReadingLessonLessonIdRoute
  '/exercises/rhythm-recognition/lesson/$lessonId': typeof ExercisesRhythmRecognitionLessonLessonIdRoute
  '/exercises/rhythm-tap-back/lesson/$lessonId': typeof ExercisesRhythmTapBackLessonLessonIdRoute
  '/exercises/silent-bar-timing/lesson/$lessonId': typeof ExercisesSilentBarTimingLessonLessonIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/presets': typeof PresetsRoute
  '/exercises/chords': typeof ExercisesChordsRoute
  '/exercises/intervals': typeof ExercisesIntervalsRoute
  '/exercises/pitch': typeof ExercisesPitchRoute
  '/exercises/rhythm': typeof ExercisesRhythmRoute
  '/exercises/chord-identification/custom': typeof ExercisesChordIdentificationCustomRoute
  '/exercises/interval-comparison/custom': typeof ExercisesIntervalComparisonCustomRoute
  '/exercises/interval-identification/custom': typeof ExercisesIntervalIdentificationCustomRoute
  '/exercises/metre-identification/custom': typeof ExercisesMetreIdentificationCustomRoute
  '/exercises/multi-interval-identification/custom': typeof ExercisesMultiIntervalIdentificationCustomRoute
  '/exercises/pitch-matching/custom': typeof ExercisesPitchMatchingCustomRoute
  '/exercises/pulse-tapping/custom': typeof ExercisesPulseTappingCustomRoute
  '/exercises/rhythm-error-detection/custom': typeof ExercisesRhythmErrorDetectionCustomRoute
  '/exercises/rhythm-reading/custom': typeof ExercisesRhythmReadingCustomRoute
  '/exercises/rhythm-recognition/custom': typeof ExercisesRhythmRecognitionCustomRoute
  '/exercises/rhythm-tap-back/custom': typeof ExercisesRhythmTapBackCustomRoute
  '/exercises/silent-bar-timing/custom': typeof ExercisesSilentBarTimingCustomRoute
  '/exercises/chord-identification': typeof ExercisesChordIdentificationIndexRoute
  '/exercises/interval-comparison': typeof ExercisesIntervalComparisonIndexRoute
  '/exercises/interval-identification': typeof ExercisesIntervalIdentificationIndexRoute
  '/exercises/metre-identification': typeof ExercisesMetreIdentificationIndexRoute
  '/exercises/multi-interval-identification': typeof ExercisesMultiIntervalIdentificationIndexRoute
  '/exercises/pitch-matching': typeof ExercisesPitchMatchingIndexRoute
  '/exercises/pulse-tapping': typeof ExercisesPulseTappingIndexRoute
  '/exercises/rhythm-error-detection': typeof ExercisesRhythmErrorDetectionIndexRoute
  '/exercises/rhythm-reading': typeof ExercisesRhythmReadingIndexRoute
  '/exercises/rhythm-recognition': typeof ExercisesRhythmRecognitionIndexRoute
  '/exercises/rhythm-tap-back': typeof ExercisesRhythmTapBackIndexRoute
  '/exercises/silent-bar-timing': typeof ExercisesSilentBarTimingIndexRoute
  '/exercises/chord-identification/lesson/$lessonId': typeof ExercisesChordIdentificationLessonLessonIdRoute
  '/exercises/interval-comparison/lesson/$lessonId': typeof ExercisesIntervalComparisonLessonLessonIdRoute
  '/exercises/interval-identification/lesson/$lessonId': typeof ExercisesIntervalIdentificationLessonLessonIdRoute
  '/exercises/metre-identification/lesson/$lessonId': typeof ExercisesMetreIdentificationLessonLessonIdRoute
  '/exercises/multi-interval-identification/lesson/$lessonId': typeof ExercisesMultiIntervalIdentificationLessonLessonIdRoute
  '/exercises/pitch-matching/lesson/$lessonId': typeof ExercisesPitchMatchingLessonLessonIdRoute
  '/exercises/pulse-tapping/lesson/$lessonId': typeof ExercisesPulseTappingLessonLessonIdRoute
  '/exercises/rhythm-error-detection/lesson/$lessonId': typeof ExercisesRhythmErrorDetectionLessonLessonIdRoute
  '/exercises/rhythm-reading/lesson/$lessonId': typeof ExercisesRhythmReadingLessonLessonIdRoute
  '/exercises/rhythm-recognition/lesson/$lessonId': typeof ExercisesRhythmRecognitionLessonLessonIdRoute
  '/exercises/rhythm-tap-back/lesson/$lessonId': typeof ExercisesRhythmTapBackLessonLessonIdRoute
  '/exercises/silent-bar-timing/lesson/$lessonId': typeof ExercisesSilentBarTimingLessonLessonIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/presets': typeof PresetsRoute
  '/exercises/chords': typeof ExercisesChordsRoute
  '/exercises/intervals': typeof ExercisesIntervalsRoute
  '/exercises/pitch': typeof ExercisesPitchRoute
  '/exercises/rhythm': typeof ExercisesRhythmRoute
  '/exercises/chord-identification/custom': typeof ExercisesChordIdentificationCustomRoute
  '/exercises/interval-comparison/custom': typeof ExercisesIntervalComparisonCustomRoute
  '/exercises/interval-identification/custom': typeof ExercisesIntervalIdentificationCustomRoute
  '/exercises/metre-identification/custom': typeof ExercisesMetreIdentificationCustomRoute
  '/exercises/multi-interval-identification/custom': typeof ExercisesMultiIntervalIdentificationCustomRoute
  '/exercises/pitch-matching/custom': typeof ExercisesPitchMatchingCustomRoute
  '/exercises/pulse-tapping/custom': typeof ExercisesPulseTappingCustomRoute
  '/exercises/rhythm-error-detection/custom': typeof ExercisesRhythmErrorDetectionCustomRoute
  '/exercises/rhythm-reading/custom': typeof ExercisesRhythmReadingCustomRoute
  '/exercises/rhythm-recognition/custom': typeof ExercisesRhythmRecognitionCustomRoute
  '/exercises/rhythm-tap-back/custom': typeof ExercisesRhythmTapBackCustomRoute
  '/exercises/silent-bar-timing/custom': typeof ExercisesSilentBarTimingCustomRoute
  '/exercises/chord-identification/': typeof ExercisesChordIdentificationIndexRoute
  '/exercises/interval-comparison/': typeof ExercisesIntervalComparisonIndexRoute
  '/exercises/interval-identification/': typeof ExercisesIntervalIdentificationIndexRoute
  '/exercises/metre-identification/': typeof ExercisesMetreIdentificationIndexRoute
  '/exercises/multi-interval-identification/': typeof ExercisesMultiIntervalIdentificationIndexRoute
  '/exercises/pitch-matching/': typeof ExercisesPitchMatchingIndexRoute
  '/exercises/pulse-tapping/': typeof ExercisesPulseTappingIndexRoute
  '/exercises/rhythm-error-detection/': typeof ExercisesRhythmErrorDetectionIndexRoute
  '/exercises/rhythm-reading/': typeof ExercisesRhythmReadingIndexRoute
  '/exercises/rhythm-recognition/': typeof ExercisesRhythmRecognitionIndexRoute
  '/exercises/rhythm-tap-back/': typeof ExercisesRhythmTapBackIndexRoute
  '/exercises/silent-bar-timing/': typeof ExercisesSilentBarTimingIndexRoute
  '/exercises/chord-identification/lesson/$lessonId': typeof ExercisesChordIdentificationLessonLessonIdRoute
  '/exercises/interval-comparison/lesson/$lessonId': typeof ExercisesIntervalComparisonLessonLessonIdRoute
  '/exercises/interval-identification/lesson/$lessonId': typeof ExercisesIntervalIdentificationLessonLessonIdRoute
  '/exercises/metre-identification/lesson/$lessonId': typeof ExercisesMetreIdentificationLessonLessonIdRoute
  '/exercises/multi-interval-identification/lesson/$lessonId': typeof ExercisesMultiIntervalIdentificationLessonLessonIdRoute
  '/exercises/pitch-matching/lesson/$lessonId': typeof ExercisesPitchMatchingLessonLessonIdRoute
  '/exercises/pulse-tapping/lesson/$lessonId': typeof ExercisesPulseTappingLessonLessonIdRoute
  '/exercises/rhythm-error-detection/lesson/$lessonId': typeof ExercisesRhythmErrorDetectionLessonLessonIdRoute
  '/exercises/rhythm-reading/lesson/$lessonId': typeof ExercisesRhythmReadingLessonLessonIdRoute
  '/exercises/rhythm-recognition/lesson/$lessonId': typeof ExercisesRhythmRecognitionLessonLessonIdRoute
  '/exercises/rhythm-tap-back/lesson/$lessonId': typeof ExercisesRhythmTapBackLessonLessonIdRoute
  '/exercises/silent-bar-timing/lesson/$lessonId': typeof ExercisesSilentBarTimingLessonLessonIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/presets'
    | '/exercises/chords'
    | '/exercises/intervals'
    | '/exercises/pitch'
    | '/exercises/rhythm'
    | '/exercises/chord-identification/custom'
    | '/exercises/interval-comparison/custom'
    | '/exercises/interval-identification/custom'
    | '/exercises/metre-identification/custom'
    | '/exercises/multi-interval-identification/custom'
    | '/exercises/pitch-matching/custom'
    | '/exercises/pulse-tapping/custom'
    | '/exercises/rhythm-error-detection/custom'
    | '/exercises/rhythm-reading/custom'
    | '/exercises/rhythm-recognition/custom'
    | '/exercises/rhythm-tap-back/custom'
    | '/exercises/silent-bar-timing/custom'
    | '/exercises/chord-identification/'
    | '/exercises/interval-comparison/'
    | '/exercises/interval-identification/'
    | '/exercises/metre-identification/'
    | '/exercises/multi-interval-identification/'
    | '/exercises/pitch-matching/'
    | '/exercises/pulse-tapping/'
    | '/exercises/rhythm-error-detection/'
    | '/exercises/rhythm-reading/'
    | '/exercises/rhythm-recognition/'
    | '/exercises/rhythm-tap-back/'
    | '/exercises/silent-bar-timing/'
    | '/exercises/chord-identification/lesson/$lessonId'
    | '/exercises/interval-comparison/lesson/$lessonId'
    | '/exercises/interval-identification/lesson/$lessonId'
    | '/exercises/metre-identification/lesson/$lessonId'
    | '/exercises/multi-interval-identification/lesson/$lessonId'
    | '/exercises/pitch-matching/lesson/$lessonId'
    | '/exercises/pulse-tapping/lesson/$lessonId'
    | '/exercises/rhythm-error-detection/lesson/$lessonId'
    | '/exercises/rhythm-reading/lesson/$lessonId'
    | '/exercises/rhythm-recognition/lesson/$lessonId'
    | '/exercises/rhythm-tap-back/lesson/$lessonId'
    | '/exercises/silent-bar-timing/lesson/$lessonId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/presets'
    | '/exercises/chords'
    | '/exercises/intervals'
    | '/exercises/pitch'
    | '/exercises/rhythm'
    | '/exercises/chord-identification/custom'
    | '/exercises/interval-comparison/custom'
    | '/exercises/interval-identification/custom'
    | '/exercises/metre-identification/custom'
    | '/exercises/multi-interval-identification/custom'
    | '/exercises/pitch-matching/custom'
    | '/exercises/pulse-tapping/custom'
    | '/exercises/rhythm-error-detection/custom'
    | '/exercises/rhythm-reading/custom'
    | '/exercises/rhythm-recognition/custom'
    | '/exercises/rhythm-tap-back/custom'
    | '/exercises/silent-bar-timing/custom'
    | '/exercises/chord-identification'
    | '/exercises/interval-comparison'
    | '/exercises/interval-identification'
    | '/exercises/metre-identification'
    | '/exercises/multi-interval-identification'
    | '/exercises/pitch-matching'
    | '/exercises/pulse-tapping'
    | '/exercises/rhythm-error-detection'
    | '/exercises/rhythm-reading'
    | '/exercises/rhythm-recognition'
    | '/exercises/rhythm-tap-back'
    | '/exercises/silent-bar-timing'
    | '/exercises/chord-identification/lesson/$lessonId'
    | '/exercises/interval-comparison/lesson/$lessonId'
    | '/exercises/interval-identification/lesson/$lessonId'
    | '/exercises/metre-identification/lesson/$lessonId'
    | '/exercises/multi-interval-identification/lesson/$lessonId'
    | '/exercises/pitch-matching/lesson/$lessonId'
    | '/exercises/pulse-tapping/lesson/$lessonId'
    | '/exercises/rhythm-error-detection/lesson/$lessonId'
    | '/exercises/rhythm-reading/lesson/$lessonId'
    | '/exercises/rhythm-recognition/lesson/$lessonId'
    | '/exercises/rhythm-tap-back/lesson/$lessonId'
    | '/exercises/silent-bar-timing/lesson/$lessonId'
  id:
    | '__root__'
    | '/'
    | '/presets'
    | '/exercises/chords'
    | '/exercises/intervals'
    | '/exercises/pitch'
    | '/exercises/rhythm'
    | '/exercises/chord-identification/custom'
    | '/exercises/interval-comparison/custom'
    | '/exercises/interval-identification/custom'
    | '/exercises/metre-identification/custom'
    | '/exercises/multi-interval-identification/custom'
    | '/exercises/pitch-matching/custom'
    | '/exercises/pulse-tapping/custom'
    | '/exercises/rhythm-error-detection/custom'
    | '/exercises/rhythm-reading/custom'
    | '/exercises/rhythm-recognition/custom'
    | '/exercises/rhythm-tap-back/custom'
    | '/exercises/silent-bar-timing/custom'
    | '/exercises/chord-identification/'
    | '/exercises/interval-comparison/'
    | '/exercises/interval-identification/'
    | '/exercises/metre-identification/'
    | '/exercises/multi-interval-identification/'
    | '/exercises/pitch-matching/'
    | '/exercises/pulse-tapping/'
    | '/exercises/rhythm-error-detection/'
    | '/exercises/rhythm-reading/'
    | '/exercises/rhythm-recognition/'
    | '/exercises/rhythm-tap-back/'
    | '/exercises/silent-bar-timing/'
    | '/exercises/chord-identification/lesson/$lessonId'
    | '/exercises/interval-comparison/lesson/$lessonId'
    | '/exercises/interval-identification/lesson/$lessonId'
    | '/exercises/metre-identification/lesson/$lessonId'
    | '/exercises/multi-interval-identification/lesson/$lessonId'
    | '/exercises/pitch-matching/lesson/$lessonId'
    | '/exercises/pulse-tapping/lesson/$lessonId'
    | '/exercises/rhythm-error-detection/lesson/$lessonId'
    | '/exercises/rhythm-reading/lesson/$lessonId'
    | '/exercises/rhythm-recognition/lesson/$lessonId'
    | '/exercises/rhythm-tap-back/lesson/$lessonId'
    | '/exercises/silent-bar-timing/lesson/$lessonId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  PresetsRoute: typeof PresetsRoute
  ExercisesChordsRoute: typeof ExercisesChordsRoute
  ExercisesIntervalsRoute: typeof ExercisesIntervalsRoute
  ExercisesPitchRoute: typeof ExercisesPitchRoute
  ExercisesRhythmRoute: typeof ExercisesRhythmRoute
  ExercisesChordIdentificationCustomRoute: typeof ExercisesChordIdentificationCustomRoute
  ExercisesIntervalComparisonCustomRoute: typeof ExercisesIntervalComparisonCustomRoute
  ExercisesIntervalIdentificationCustomRoute: typeof ExercisesIntervalIdentificationCustomRoute
  ExercisesMetreIdentificationCustomRoute: typeof ExercisesMetreIdentificationCustomRoute
  ExercisesMultiIntervalIdentificationCustomRoute: typeof ExercisesMultiIntervalIdentificationCustomRoute
  ExercisesPitchMatchingCustomRoute: typeof ExercisesPitchMatchingCustomRoute
  ExercisesPulseTappingCustomRoute: typeof ExercisesPulseTappingCustomRoute
  ExercisesRhythmErrorDetectionCustomRoute: typeof ExercisesRhythmErrorDetectionCustomRoute
  ExercisesRhythmReadingCustomRoute: typeof ExercisesRhythmReadingCustomRoute
  ExercisesRhythmRecognitionCustomRoute: typeof ExercisesRhythmRecognitionCustomRoute
  ExercisesRhythmTapBackCustomRoute: typeof ExercisesRhythmTapBackCustomRoute
  ExercisesSilentBarTimingCustomRoute: typeof ExercisesSilentBarTimingCustomRoute
  ExercisesChordIdentificationIndexRoute: typeof ExercisesChordIdentificationIndexRoute
  ExercisesIntervalComparisonIndexRoute: typeof ExercisesIntervalComparisonIndexRoute
  ExercisesIntervalIdentificationIndexRoute: typeof ExercisesIntervalIdentificationIndexRoute
  ExercisesMetreIdentificationIndexRoute: typeof ExercisesMetreIdentificationIndexRoute
  ExercisesMultiIntervalIdentificationIndexRoute: typeof ExercisesMultiIntervalIdentificationIndexRoute
  ExercisesPitchMatchingIndexRoute: typeof ExercisesPitchMatchingIndexRoute
  ExercisesPulseTappingIndexRoute: typeof ExercisesPulseTappingIndexRoute
  ExercisesRhythmErrorDetectionIndexRoute: typeof ExercisesRhythmErrorDetectionIndexRoute
  ExercisesRhythmReadingIndexRoute: typeof ExercisesRhythmReadingIndexRoute
  ExercisesRhythmRecognitionIndexRoute: typeof ExercisesRhythmRecognitionIndexRoute
  ExercisesRhythmTapBackIndexRoute: typeof ExercisesRhythmTapBackIndexRoute
  ExercisesSilentBarTimingIndexRoute: typeof ExercisesSilentBarTimingIndexRoute
  ExercisesChordIdentificationLessonLessonIdRoute: typeof ExercisesChordIdentificationLessonLessonIdRoute
  ExercisesIntervalComparisonLessonLessonIdRoute: typeof ExercisesIntervalComparisonLessonLessonIdRoute
  ExercisesIntervalIdentificationLessonLessonIdRoute: typeof ExercisesIntervalIdentificationLessonLessonIdRoute
  ExercisesMetreIdentificationLessonLessonIdRoute: typeof ExercisesMetreIdentificationLessonLessonIdRoute
  ExercisesMultiIntervalIdentificationLessonLessonIdRoute: typeof ExercisesMultiIntervalIdentificationLessonLessonIdRoute
  ExercisesPitchMatchingLessonLessonIdRoute: typeof ExercisesPitchMatchingLessonLessonIdRoute
  ExercisesPulseTappingLessonLessonIdRoute: typeof ExercisesPulseTappingLessonLessonIdRoute
  ExercisesRhythmErrorDetectionLessonLessonIdRoute: typeof ExercisesRhythmErrorDetectionLessonLessonIdRoute
  ExercisesRhythmReadingLessonLessonIdRoute: typeof ExercisesRhythmReadingLessonLessonIdRoute
  ExercisesRhythmRecognitionLessonLessonIdRoute: typeof ExercisesRhythmRecognitionLessonLessonIdRoute
  ExercisesRhythmTapBackLessonLessonIdRoute: typeof ExercisesRhythmTapBackLessonLessonIdRoute
  ExercisesSilentBarTimingLessonLessonIdRoute: typeof ExercisesSilentBarTimingLessonLessonIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/presets': {
      id: '/presets'
      path: '/presets'
      fullPath: '/presets'
      preLoaderRoute: typeof PresetsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/exercises/chords': {
      id: '/exercises/chords'
      path: '/exercises/chords'
      fullPath: '/exercises/chords'
      preLoaderRoute: typeof ExercisesChordsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/exercises/intervals': {
      id: '/exercises/intervals'
      path: '/exercises/intervals'
      fullPath: '/exercises/intervals'
      preLoaderRoute: typeof ExercisesIntervalsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/exercises/pitch': {
      id: '/exercises/pitch'
      path: '/exercises/pitch'
      fullPath: '/exercises/pitch'
      preLoaderRoute: typeof ExercisesPitchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/exercises/rhythm': {
      id: '/exercises/rhythm'
      path: '/exercises/rhythm'
      fullPath: '/exercises/rhythm'
      preLoaderRoute: typeof ExercisesRhythmRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/exercises/chord-identification/': {
      id: '/exercises/chord-identification/'
      path: '/exercises/chord-identification'
      fullPath: '/exercises/chord-identification/'
      preLoaderRoute: typeof ExercisesChordIdentificationIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/exercises/chord-identification/custom': {
      id: '/exercises/chord-identification/custom'
      path: '/exercises/chord-identification/custom'
      fullPath: '/exercises/chord-identification/custom'
      preLoaderRoute: typeof ExercisesChordIdentificationCustomRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/exercises/interval-comparison/': {
      id: '/exercises/interval-comparison/'
      path: '/exercises/interval-comparison'
      fullPath: '/exercises/interval-comparison/'
      preLoaderRoute: typeof ExercisesIntervalComparisonIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/exercises/interval-comparison/custom': {
      id: '/exercises/interval-comparison/custom'
      path: '/exercises/interval-comparison/custom'
      fullPath: '/exercises/interval-comparison/custom'
      preLoaderRoute: typeof ExercisesIntervalComparisonCustomRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/exercises/interval-identification/': {
      id: '/exercises/interval-identification/'
      path: '/exercises/interval-identification'
      fullPath: '/exercises/interval-identification/'
      preLoaderRoute: typeof ExercisesIntervalIdentificationIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/exercises/interval-identification/custom': {
      id: '/exercises/interval-identification/custom'
      path: '/exercises/interval-identification/custom'
      fullPath: '/exercises/interval-identification/custom'
      preLoaderRoute: typeof ExercisesIntervalIdentificationCustomRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/exercises/metre-identification/': {
      id: '/exercises/metre-identification/'
      path: '/exercises/metre-identification'
      fullPath: '/exercises/metre-identification/'
      preLoaderRoute: typeof ExercisesMetreIdentificationIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/exercises/metre-identification/custom': {
      id: '/exercises/metre-identification/custom'
      path: '/exercises/metre-identification/custom'
      fullPath: '/exercises/metre-identification/custom'
      preLoaderRoute: typeof ExercisesMetreIdentificationCustomRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/exercises/multi-interval-identification/': {
      id: '/exercises/multi-interval-identification/'
      path: '/exercises/multi-interval-identification'
      fullPath: '/exercises/multi-interval-identification/'
      preLoaderRoute: typeof ExercisesMultiIntervalIdentificationIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/exercises/multi-interval-identification/custom': {
      id: '/exercises/multi-interval-identification/custom'
      path: '/exercises/multi-interval-identification/custom'
      fullPath: '/exercises/multi-interval-identification/custom'
      preLoaderRoute: typeof ExercisesMultiIntervalIdentificationCustomRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/exercises/pitch-matching/': {
      id: '/exercises/pitch-matching/'
      path: '/exercises/pitch-matching'
      fullPath: '/exercises/pitch-matching/'
      preLoaderRoute: typeof ExercisesPitchMatchingIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/exercises/pitch-matching/custom': {
      id: '/exercises/pitch-matching/custom'
      path: '/exercises/pitch-matching/custom'
      fullPath: '/exercises/pitch-matching/custom'
      preLoaderRoute: typeof ExercisesPitchMatchingCustomRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/exercises/pulse-tapping/': {
      id: '/exercises/pulse-tapping/'
      path: '/exercises/pulse-tapping'
      fullPath: '/exercises/pulse-tapping/'
      preLoaderRoute: typeof ExercisesPulseTappingIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/exercises/pulse-tapping/custom': {
      id: '/exercises/pulse-tapping/custom'
      path: '/exercises/pulse-tapping/custom'
      fullPath: '/exercises/pulse-tapping/custom'
      preLoaderRoute: typeof ExercisesPulseTappingCustomRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/exercises/rhythm-error-detection/': {
      id: '/exercises/rhythm-error-detection/'
      path: '/exercises/rhythm-error-detection'
      fullPath: '/exercises/rhythm-error-detection/'
      preLoaderRoute: typeof ExercisesRhythmErrorDetectionIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/exercises/rhythm-error-detection/custom': {
      id: '/exercises/rhythm-error-detection/custom'
      path: '/exercises/rhythm-error-detection/custom'
      fullPath: '/exercises/rhythm-error-detection/custom'
      preLoaderRoute: typeof ExercisesRhythmErrorDetectionCustomRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/exercises/rhythm-reading/': {
      id: '/exercises/rhythm-reading/'
      path: '/exercises/rhythm-reading'
      fullPath: '/exercises/rhythm-reading/'
      preLoaderRoute: typeof ExercisesRhythmReadingIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/exercises/rhythm-reading/custom': {
      id: '/exercises/rhythm-reading/custom'
      path: '/exercises/rhythm-reading/custom'
      fullPath: '/exercises/rhythm-reading/custom'
      preLoaderRoute: typeof ExercisesRhythmReadingCustomRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/exercises/rhythm-recognition/': {
      id: '/exercises/rhythm-recognition/'
      path: '/exercises/rhythm-recognition'
      fullPath: '/exercises/rhythm-recognition/'
      preLoaderRoute: typeof ExercisesRhythmRecognitionIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/exercises/rhythm-recognition/custom': {
      id: '/exercises/rhythm-recognition/custom'
      path: '/exercises/rhythm-recognition/custom'
      fullPath: '/exercises/rhythm-recognition/custom'
      preLoaderRoute: typeof ExercisesRhythmRecognitionCustomRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/exercises/rhythm-tap-back/': {
      id: '/exercises/rhythm-tap-back/'
      path: '/exercises/rhythm-tap-back'
      fullPath: '/exercises/rhythm-tap-back/'
      preLoaderRoute: typeof ExercisesRhythmTapBackIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/exercises/rhythm-tap-back/custom': {
      id: '/exercises/rhythm-tap-back/custom'
      path: '/exercises/rhythm-tap-back/custom'
      fullPath: '/exercises/rhythm-tap-back/custom'
      preLoaderRoute: typeof ExercisesRhythmTapBackCustomRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/exercises/silent-bar-timing/': {
      id: '/exercises/silent-bar-timing/'
      path: '/exercises/silent-bar-timing'
      fullPath: '/exercises/silent-bar-timing/'
      preLoaderRoute: typeof ExercisesSilentBarTimingIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/exercises/silent-bar-timing/custom': {
      id: '/exercises/silent-bar-timing/custom'
      path: '/exercises/silent-bar-timing/custom'
      fullPath: '/exercises/silent-bar-timing/custom'
      preLoaderRoute: typeof ExercisesSilentBarTimingCustomRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/exercises/chord-identification/lesson/$lessonId': {
      id: '/exercises/chord-identification/lesson/$lessonId'
      path: '/exercises/chord-identification/lesson/$lessonId'
      fullPath: '/exercises/chord-identification/lesson/$lessonId'
      preLoaderRoute: typeof ExercisesChordIdentificationLessonLessonIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/exercises/interval-comparison/lesson/$lessonId': {
      id: '/exercises/interval-comparison/lesson/$lessonId'
      path: '/exercises/interval-comparison/lesson/$lessonId'
      fullPath: '/exercises/interval-comparison/lesson/$lessonId'
      preLoaderRoute: typeof ExercisesIntervalComparisonLessonLessonIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/exercises/interval-identification/lesson/$lessonId': {
      id: '/exercises/interval-identification/lesson/$lessonId'
      path: '/exercises/interval-identification/lesson/$lessonId'
      fullPath: '/exercises/interval-identification/lesson/$lessonId'
      preLoaderRoute: typeof ExercisesIntervalIdentificationLessonLessonIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/exercises/metre-identification/lesson/$lessonId': {
      id: '/exercises/metre-identification/lesson/$lessonId'
      path: '/exercises/metre-identification/lesson/$lessonId'
      fullPath: '/exercises/metre-identification/lesson/$lessonId'
      preLoaderRoute: typeof ExercisesMetreIdentificationLessonLessonIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/exercises/multi-interval-identification/lesson/$lessonId': {
      id: '/exercises/multi-interval-identification/lesson/$lessonId'
      path: '/exercises/multi-interval-identification/lesson/$lessonId'
      fullPath: '/exercises/multi-interval-identification/lesson/$lessonId'
      preLoaderRoute: typeof ExercisesMultiIntervalIdentificationLessonLessonIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/exercises/pitch-matching/lesson/$lessonId': {
      id: '/exercises/pitch-matching/lesson/$lessonId'
      path: '/exercises/pitch-matching/lesson/$lessonId'
      fullPath: '/exercises/pitch-matching/lesson/$lessonId'
      preLoaderRoute: typeof ExercisesPitchMatchingLessonLessonIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/exercises/pulse-tapping/lesson/$lessonId': {
      id: '/exercises/pulse-tapping/lesson/$lessonId'
      path: '/exercises/pulse-tapping/lesson/$lessonId'
      fullPath: '/exercises/pulse-tapping/lesson/$lessonId'
      preLoaderRoute: typeof ExercisesPulseTappingLessonLessonIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/exercises/rhythm-error-detection/lesson/$lessonId': {
      id: '/exercises/rhythm-error-detection/lesson/$lessonId'
      path: '/exercises/rhythm-error-detection/lesson/$lessonId'
      fullPath: '/exercises/rhythm-error-detection/lesson/$lessonId'
      preLoaderRoute: typeof ExercisesRhythmErrorDetectionLessonLessonIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/exercises/rhythm-reading/lesson/$lessonId': {
      id: '/exercises/rhythm-reading/lesson/$lessonId'
      path: '/exercises/rhythm-reading/lesson/$lessonId'
      fullPath: '/exercises/rhythm-reading/lesson/$lessonId'
      preLoaderRoute: typeof ExercisesRhythmReadingLessonLessonIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/exercises/rhythm-recognition/lesson/$lessonId': {
      id: '/exercises/rhythm-recognition/lesson/$lessonId'
      path: '/exercises/rhythm-recognition/lesson/$lessonId'
      fullPath: '/exercises/rhythm-recognition/lesson/$lessonId'
      preLoaderRoute: typeof ExercisesRhythmRecognitionLessonLessonIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/exercises/rhythm-tap-back/lesson/$lessonId': {
      id: '/exercises/rhythm-tap-back/lesson/$lessonId'
      path: '/exercises/rhythm-tap-back/lesson/$lessonId'
      fullPath: '/exercises/rhythm-tap-back/lesson/$lessonId'
      preLoaderRoute: typeof ExercisesRhythmTapBackLessonLessonIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/exercises/silent-bar-timing/lesson/$lessonId': {
      id: '/exercises/silent-bar-timing/lesson/$lessonId'
      path: '/exercises/silent-bar-timing/lesson/$lessonId'
      fullPath: '/exercises/silent-bar-timing/lesson/$lessonId'
      preLoaderRoute: typeof ExercisesSilentBarTimingLessonLessonIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  PresetsRoute: PresetsRoute,
  ExercisesChordsRoute: ExercisesChordsRoute,
  ExercisesIntervalsRoute: ExercisesIntervalsRoute,
  ExercisesPitchRoute: ExercisesPitchRoute,
  ExercisesRhythmRoute: ExercisesRhythmRoute,
  ExercisesChordIdentificationCustomRoute:
    ExercisesChordIdentificationCustomRoute,
  ExercisesIntervalComparisonCustomRoute:
    ExercisesIntervalComparisonCustomRoute,
  ExercisesIntervalIdentificationCustomRoute:
    ExercisesIntervalIdentificationCustomRoute,
  ExercisesMetreIdentificationCustomRoute:
    ExercisesMetreIdentificationCustomRoute,
  ExercisesMultiIntervalIdentificationCustomRoute:
    ExercisesMultiIntervalIdentificationCustomRoute,
  ExercisesPitchMatchingCustomRoute: ExercisesPitchMatchingCustomRoute,
  ExercisesPulseTappingCustomRoute: ExercisesPulseTappingCustomRoute,
  ExercisesRhythmErrorDetectionCustomRoute:
    ExercisesRhythmErrorDetectionCustomRoute,
  ExercisesRhythmReadingCustomRoute: ExercisesRhythmReadingCustomRoute,
  ExercisesRhythmRecognitionCustomRoute: ExercisesRhythmRecognitionCustomRoute,
  ExercisesRhythmTapBackCustomRoute: ExercisesRhythmTapBackCustomRoute,
  ExercisesSilentBarTimingCustomRoute: ExercisesSilentBarTimingCustomRoute,
  ExercisesChordIdentificationIndexRoute:
    ExercisesChordIdentificationIndexRoute,
  ExercisesIntervalComparisonIndexRoute: ExercisesIntervalComparisonIndexRoute,
  ExercisesIntervalIdentificationIndexRoute:
    ExercisesIntervalIdentificationIndexRoute,
  ExercisesMetreIdentificationIndexRoute:
    ExercisesMetreIdentificationIndexRoute,
  ExercisesMultiIntervalIdentificationIndexRoute:
    ExercisesMultiIntervalIdentificationIndexRoute,
  ExercisesPitchMatchingIndexRoute: ExercisesPitchMatchingIndexRoute,
  ExercisesPulseTappingIndexRoute: ExercisesPulseTappingIndexRoute,
  ExercisesRhythmErrorDetectionIndexRoute:
    ExercisesRhythmErrorDetectionIndexRoute,
  ExercisesRhythmReadingIndexRoute: ExercisesRhythmReadingIndexRoute,
  ExercisesRhythmRecognitionIndexRoute: ExercisesRhythmRecognitionIndexRoute,
  ExercisesRhythmTapBackIndexRoute: ExercisesRhythmTapBackIndexRoute,
  ExercisesSilentBarTimingIndexRoute: ExercisesSilentBarTimingIndexRoute,
  ExercisesChordIdentificationLessonLessonIdRoute:
    ExercisesChordIdentificationLessonLessonIdRoute,
  ExercisesIntervalComparisonLessonLessonIdRoute:
    ExercisesIntervalComparisonLessonLessonIdRoute,
  ExercisesIntervalIdentificationLessonLessonIdRoute:
    ExercisesIntervalIdentificationLessonLessonIdRoute,
  ExercisesMetreIdentificationLessonLessonIdRoute:
    ExercisesMetreIdentificationLessonLessonIdRoute,
  ExercisesMultiIntervalIdentificationLessonLessonIdRoute:
    ExercisesMultiIntervalIdentificationLessonLessonIdRoute,
  ExercisesPitchMatchingLessonLessonIdRoute:
    ExercisesPitchMatchingLessonLessonIdRoute,
  ExercisesPulseTappingLessonLessonIdRoute:
    ExercisesPulseTappingLessonLessonIdRoute,
  ExercisesRhythmErrorDetectionLessonLessonIdRoute:
    ExercisesRhythmErrorDetectionLessonLessonIdRoute,
  ExercisesRhythmReadingLessonLessonIdRoute:
    ExercisesRhythmReadingLessonLessonIdRoute,
  ExercisesRhythmRecognitionLessonLessonIdRoute:
    ExercisesRhythmRecognitionLessonLessonIdRoute,
  ExercisesRhythmTapBackLessonLessonIdRoute:
    ExercisesRhythmTapBackLessonLessonIdRoute,
  ExercisesSilentBarTimingLessonLessonIdRoute:
    ExercisesSilentBarTimingLessonLessonIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
